Feature/part18 badge
alex-b1/test-guru pull request #18
Opened 2021-05-23 14:52 UTC by alex-b1

2021-05-23 16:33 UTC, BubuntuClu requested changes

2021-05-23 16:33 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def set_user_badges
что-то я сильно сомневаюсь что это надо помещать в applcation_controller. на каждый запрос показывать бейджи. зачем? лучше сделать отдельный раздел где можно посомтреть свои бейджи

2021-05-23 16:33 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :set_user_badges
это же есть в application_controller

2021-05-23 16:33 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      admin = Admin.first
а причем тут админ? почему методы вызываются от объекта админа? сделай сервис вместо этого

2021-05-23 16:33 UTC, BubuntuClu commented on app/models/admin.rb
> +class Admin < User
всю эту логику надо поместить в сервис. админ модель тут вообще не причем

2021-05-23 16:33 UTC, BubuntuClu commented on app/models/admin.rb
> +    check_all_geography(user, test_id)
на каждый новый бейдж надо будет дописывать тут строки? не очень удобно.
сделай перебор бейджей и на каждый вызывай метод на основе имени правила бейджа, что-то типа `send("#{badge.rule}_award?")`

2021-05-23 16:33 UTC, BubuntuClu commented on app/models/admin.rb
> +    Test.where(category_id: CATEGORY_GEOGRAPHY).each {|i| pass_cat_geography = false unless success_tests.include?(i.id)}
логику выборки/сортировки/фильтрации максимально выноси в БД

у тебя в итоге получится два запроса, результат которых надо сравнить. рубишной манипуляции с данными тут не нужны

2021-05-23 16:33 UTC, BubuntuClu commented on app/models/admin.rb
> +    rule_first_attempt = Rule.find_by(title: 'first_attempt')
как используется эта переменная?

2021-05-24 07:31 UTC, BubuntuClu requested changes

2021-05-24 07:31 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    test_pass = user.test_passages.where(test_id: user.test_passages.order(:id).last.test_id)
передай в сервис только что прошедший тест. он у тебя есть в контроллере, а ты его тут еще раз ищешь

2021-05-24 07:31 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    rule_all_geography = Rule.find_by(title: 'all_geography')
ты перебираешь правила, и для правила вызываешь метод, но внутри правила опять ищешь само правило? зачем так? почему не передать правило в метод?

2021-05-24 07:31 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    Rule.all.each { |i| send("#{i.title}_rule", user) }
```
Badge.all.each do |badge|
  set_user_badges(user, badge) if  send("#{badlge.rule.title}_award?", badge.value)
end
```
мне кажется прохолдить по бейджам лучше, так как тебе не надо искать их чтобы потом засунуть в пользователя. так же само правило тебе по сути не нужно, от него надо только название

2021-05-24 07:31 UTC, BubuntuClu commented on app/services/badge_service.rb
> +
стоит добавить инициализацию, чтобы сохранить параметры, которые ты юзаешь в своих методах, типа пользователя и теста

2021-05-24 07:31 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    user.test_passages.each {|i| success_tests.push(i.test_id) if i.success? }
надо заменить на запрос. добавь поле в таблицу, чтобы можно было фильтровать по успешным тестам

2021-05-24 18:53 UTC, BubuntuClu requested changes

2021-05-24 18:53 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      @test_passage.result = !!@test_passage.success?
```
if @test_passage.success?
  @test_passage.update(result: true)
  BadgeService.new(current_user, @test_passage).call
```
нет смысла бейджи давать если тест не пройден успешно

2021-05-24 18:53 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      badge_service.rules
в сервисе обычно делают метод `call`, который запускает логику

2021-05-24 18:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      badge.rules.each { |i| set_user_badges(badge) if  send("#{i.title}_rule", i) }
а зачем бейджу иметь несколько правил? это конечно делает гибкость в будущем, когда можно комбинировать правила, но сейчас в чем смысл?

и давай переменным нормальные имена. что такое `i`? ты итерируешь правила, сделай `rule`

2021-05-24 18:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    !!(test_pass&.count == 1 && test_pass[0].test.questions.count == test_pass[0].correct_questions)
зачем двойное отрицание?

вообще тут тебе надо просто сравнить, у пользователя прохождений этого теста только одно? зачем сравнивать ответы? ты запускаешь выдачу бейджей только для успешных прохождений. это условие становится лишним

2021-05-24 18:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @user.rule_passages.create(rule_id: rule.id) if !pass_all_geography && pass_cat_geography
`pass_all_geography.blank?  && pass_cat_geography`, мне кажется, так выглядит понятней чего ты хочешь от этого условия

2021-05-24 18:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    !!(test_pass&.count == 1 && test_pass[0].test.questions.count == test_pass[0].correct_questions)
и тут ты забыл добавить 
`@user.rule_passages.create(rule_id: rule.id) if !pass_all_level_2 && pass_level_2`
подобное услвоие для этого правила

2021-05-24 18:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    success_tests = set_success_tests
это выглядит как метод в пассажах с аргументом тест_ид

2021-05-24 18:53 UTC, BubuntuClu commented on db/migrate/20210524101308_add_reference_rule_to_badge.rb
> +    add_reference :rules, :badge, index: true
внешний ключ еще добавить надо

2021-05-24 18:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    pass_all_geography = @user.rule_passages.find_by(rule_id: rule.id)
можешь объяснить смысл таблицы `rule_passages`? 
у тебя есть  `user_badges` где хранятся связи пользователя с бейджами. а вот зачем связывать прохождения тестов с правила, я чет не понимаю

2021-05-24 21:05 UTC, alex-b1 commented on app/services/badge_service.rb
> +      badge.rules.each { |i| set_user_badges(badge) if  send("#{i.title}_rule", i) }
у меня на золотую медаль 2 правила (все категории и все тесты одного уровня) и да гибкость в будущем , м.б завтра еще одно правило допишу, не таблицу же переделывать

2021-05-24 21:15 UTC, alex-b1 commented on app/services/badge_service.rb
> +    !!(test_pass&.count == 1 && test_pass[0].test.questions.count == test_pass[0].correct_questions)
а здесь эта проверка лишняя, если в двух других правилах бейдж может выдаваться только один раз, (ответив на все вопросы из категории получили бейдж, при повторном ответе на любой из тестов в категории бейдж бы давался еще один, правило бы не работало), а здесь медаль выдается за первое успешное прохождение любого из тестов

2021-05-24 21:43 UTC, alex-b1 commented on app/services/badge_service.rb
> +    pass_all_geography = @user.rule_passages.find_by(rule_id: rule.id)
золотой бейдж выдается один раз за правило, 1 раз за прохождение всех категорий и 1 раз за прохождение всех тестов определенного уровня, в таблице rule_passages делаем запись, что такое правило уже пройдем, иначе при попытке пройти тест , мы получим медаль еще раз , (проходим 3 теста с категорией 1, получаем медаль, проходим еще один раз  тест из тестов с категорий 1 медаль опять будет выдана), но дня некоторых правил, бейдж может выдаваться по несколько раз, в этом случаи запись не делаем

2021-05-25 07:20 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :success_tests, -> {where(result: true).pluck(:test_id).uniq}
вспоминай - https://github.com/alex-b1/test-guru/pull/5#discussion_r625327864
pluck нельзя помещать в скоуп

2021-05-25 07:20 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :success_tests, -> {where(result: true).pluck(:test_id).uniq}
ты выбираешь прохождения всех тестов всеми пользователями, а надо конкретного пользователя

2021-05-25 08:00 UTC, merged