Feature/part10
alex-b1/test-guru pull request #9
Opened 2021-05-09 15:40 UTC by alex-b1

2021-05-09 17:55 UTC, BubuntuClu requested changes

2021-05-09 17:55 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +      cookies[:path] = request.url
path - неочень понятное имя. путь чего или для чего? нужно более понятное описание переменной

2021-05-09 17:55 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
можно поместить этот метод в родительский контроллер и тогда не надо будет прописывать везде этот колбэк

2021-05-09 17:55 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if cookies[:path]
`redirect_to cookies[ключ_с_понятным_неймингом] || tests_path`

2021-05-09 17:55 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def find_user
этот метод тебе больше не нужен. теперь у тебя есть метод `current_user`, который возвращает тебе пользователя авторизованного

2021-05-09 17:55 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
`validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }`

2021-05-09 17:55 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
5 и 6 строка дублируют путь на 10 и 11 стоках. надо убрать дублирование

2021-05-09 17:55 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, uniqueness: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2021-05-09 18:24 UTC, alex-b1 commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
сделать метод в родительском контролере в котором вызывать колбэк , а потом это метод добавить в нужные контрлеры так что ли ? выглядит как-то странно. Или вызывать этот колбэк в родительском контролере? так он не для всех контролеров нужен. Или сделать еще один промежуточный контроллер ?

2021-05-09 18:34 UTC, alex-b1 commented on app/controllers/sessions_controller.rb
> +      if cookies[:path]
у меня ж там еще удаление идет redirect_to cookies.delete :path, такой вариант cookies[ключ_с_понятным_неймингом] || tests_path  кажется не очень очеведным

2021-05-10 10:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
сейчас он у тебя потчи во всех контроллерах нужен. чтобы не выполнился колбэк, скипаешь его для нужного метода в контроллере

2021-05-10 10:54 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if cookies[:path]
а зачем удалять при редиректе. имхо стоит удалять, при логауте

2021-05-10 15:20 UTC, alex-b1 commented on app/controllers/sessions_controller.rb
> +      if cookies[:path]
так сессия и при закрытие браузера протухает, если логаут не делали, а браузер закрыли при новом открытии редиректнет не туда

2021-05-10 15:28 UTC, alex-b1 commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
а как 'скипать' ? написать метод skip_authenticate в родительском и в нужных контроллерах переопределять его, чтобы true возвращал ?

2021-05-10 15:36 UTC, merged